version: '3.8'

# Development docker-compose with hot-reload
services:
  redis:
    image: redis:7-alpine
    container_name: dmm-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - dmm-network

  # Backend API (development mode with hot-reload)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dmm-backend-dev
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "6801:6800"  # aria2c RPC
    volumes:
      - ./backend:/app/backend
      - ./config:/config
      - ./data/downloads:/downloads
      - ./data/media:/media
      - ./data/cache:/cache
      - ./logs:/app/logs
    environment:
      - APP_ENV=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=sqlite:////config/database.db
      - REDIS_URL=redis://redis:6379/0
      - TMDB_API_KEY=${TMDB_API_KEY:-}
      - ENABLE_CORS=true
      - CORS_ORIGINS=http://localhost:3001,http://localhost:8081
    working_dir: /app/backend
    depends_on:
      - redis
    networks:
      - dmm-network

  # Frontend (development server with hot-reload)
  frontend:
    image: node:18-alpine
    container_name: dmm-frontend-dev
    working_dir: /app
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - dmm-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

networks:
  dmm-network:
    driver: bridge
